modLoader="javafml"
loaderVersion="[45,)"
license="GNU Affero General Public License v3.0"
issueTrackerURL="https://github.com/Viola-Siemens/Tales-of-Villagers-The-Infiltrators/issues"

[[mods]]
modId="infiltrators"
version="${file.jarVersion}"
displayName="Tales of Villagers: The Infiltrators"
displayURL="https://github.com/Viola-Siemens/Tales-of-Villagers-The-Infiltrators"
logoFile="logo.png"
credits="Hexagram"
authors="Liu Dongyu"
description='''
This mod adds some "fake villagers", the infiltrators, who will fake their works and prevent other villagers from working.

Also, when raids occur, the Infiltrators will convert into illagers, and help other illagers attack other villagers.

Can you still beat the game and save the village?
'''

[[dependencies.infiltrators]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.infiltrators]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
